version: '3'
services:
  api:
    image: node:16.15.1
    working_dir: /code
    volumes:
      - type: bind
        source: ./api
        target: /code
  db:
    image: postgres:12.4
    environment:
      - POSTGRES_USER=futureproof
    volumes:
      - './db:/docker-entrypoint-initdb.d/:ro'
